name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        build-type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get install -y gstreamer1.0-tools libgstreamer1.0-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ..
          make
      - name: Test
        run: |
          export GST_PLUGIN_PATH="${PWD}/build/gst-plugin"
          gst-inspect-1.0 | grep fakeplugin
